apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: test
  name: php-apache-ds
spec:
  selector:
    matchLabels:
      run: php-apache-ds
  template:
    metadata:
      labels:
        run: php-apache-ds
    spec:
      containers:
      - name: php-apache-ds
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: php-apache-ds
  labels:
    run: php-apache-ds
spec:
  ports:
  - port: 80
  selector:
    run: php-apache-ds
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: test
  name: php-apache-ds-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: php-apache-ds
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50