# This config file contains
# Ingress setup (https://kind.sigs.k8s.io/docs/user/ingress/)
# Portainer setup (extraMounts + port 9000)
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
    # hostPath must match the path to the dist folder of the portainer project
  - hostPath: /home/baron_l/projects/pro/portainer/dist
    containerPath: /portainer/app
  extraPortMappings:
  - containerPort: 9000
    hostPort: 9020
  - containerPort: 8000
    hostPort: 8020
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
