apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer
spec:
  selector:
    matchLabels:
      run: portainer
  template:
    metadata:
      labels:
        run: portainer
    spec:
      serviceAccountName: portainer-sa-clusteradmin
      containers:
      - name: portainer
        image: portainer/base
        # imagePullPolicy: "Never"
        command: ["/app/portainer"]
        args: ["--no-analytics",]
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 8000
          hostPort: 8000
        volumeMounts:
        - mountPath: /app
          name: portainer-dist
      volumes:
      - name: portainer-dist
        hostPath:
          path: /portainer/app
          type: Directory
